// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  urlAddress: 'http://localhost:24813',
  urlAddress1: 'http://localhost:24813/#/',
  urlAddress4200: 'http://localhost:4200/#/',
  Domain: 'http://localhost:24813/',
  APIUrl: 'http://localhost:24813/api/',
  getMacAddress: 'http://localhost:24813/api/Error/GetMacAddress',
  getMBSerial: 'http://localhost:24813/api/Error/GetMBSerial',
  FilePath: 'http://localhost:24813/',
  ListRoleCategories: "http://localhost:24813/api/RoleCategory/ListRoleCategories",
  AddRoleCategory: "http://localhost:24813/api/RoleCategory/AddRoleCategory",
  GetRoleCategoryById: "http://localhost:24813/api/RoleCategory/GetById/",
  UpdateRoleCategory: "http://localhost:24813/api/RoleCategory/UpdateRoleCategory",
  DeleteRoleCategory: "http://localhost:24813/api/RoleCategory/DeleteRoleCategory/",

  SortRoleCategories: "http://localhost:24813/api/RoleCategory/SortRoleCategories/",
  GenerateRoleCategoryOrderId: "http://localhost:24813/api/RoleCategory/GenerateRoleCategoryOrderId",
  ListRoles: "http://localhost:24813/api/Role/ListRoles",
  ListRolesWithPaging: "http://localhost:24813/api/Role/ListRolesWithPages/",
  getRolescount: "http://localhost:24813/api/Role/getcount/",
  AddRole: "http://localhost:24813/api/Role/AddRole",
  GetRoleById: "http://localhost:24813/api/Role/GetById/",
  GetRolesByRoleCategoryId: "http://localhost:24813/api/Role/GetRolesByRoleCategoryId/",
  AddRoleToListById: "http://localhost:24813/api/Role/AddRoleToListById/",
  UpdateRole: "http://localhost:24813/api/Role/UpdateRole",
  DeleteRole: "http://localhost:24813/api/Role/DeleteRole/",
  ListOrganizations: "http://localhost:24813/api/Organization/ListOrganizations",
  AddOrganization: "http://localhost:24813/api/Organization/AddOrganization",
  GetOrganizationById: "http://localhost:24813/api/Organization/GetById/",
  UpdateOrganization: "http://localhost:24813/api/Organization/UpdateOrganization",
  DeleteOrganization: "http://localhost:24813/api/Organization/DeleteOrganization/",
  ListSubOrganizations: "http://localhost:24813/api/SubOrganization/ListSubOrganizations",
  AddSubOrganization: "http://localhost:24813/api/SubOrganization/AddSubOrganization",
  GetSubOrganizationById: "http://localhost:24813/api/SubOrganization/GetById/",
  GetSubOrganizationByOrgId: "http://localhost:24813/api/SubOrganization/GetSubOrganizationByOrgId/",
  UpdateSubOrganization: "http://localhost:24813/api/SubOrganization/UpdateSubOrganization",
  DeleteSubOrganization: "http://localhost:24813/api/SubOrganization/DeleteSubOrganization/",
  GetOrganizationBySubId: "http://localhost:24813/api/SubOrganization/GetOrganizationBySubId/",
  ListGovernorates: "http://localhost:24813/api/Governorate/ListGovernorates",
  AddGovernorate: "http://localhost:24813/api/Governorate/AddGovernorate",
  GetGovernorateById: "http://localhost:24813/api/Governorate/GetById/",
  GetGovernorateByName: "http://localhost:24813/api/Governorate/GetGovernorateByName/",
  UpdateGovernorate: "http://localhost:24813/api/Governorate/UpdateGovernorate",
  DeleteGovernorate: "http://localhost:24813/api/Governorate/DeleteGovernorate/",
  GetGovernorateWithHos: "http://localhost:24813/api/Governorate/GetGovernorateWithHospitals/",
  ListCities: "http://localhost:24813/api/City/ListCities",
  AddCity: "http://localhost:24813/api/City/AddCity",
  GetCityById: "http://localhost:24813/api/City/GetById/",
  UpdateCity: "http://localhost:24813/api/City/UpdateCity",
  DeleteCity: "http://localhost:24813/api/City/DeleteCity/",
  getCityIdByName: 'http://localhost:24813/api/City/GetCityIdByName/',
  GetCitiesByGovernorateId: "http://localhost:24813/api/City/GetCitiesByGovernorateId/",
  GetCitiesByGovernorateName: "http://localhost:24813/api/City/GetCitiesByGovernorateName/",
  GetGovIdByname: 'http://localhost:24813/api/City/GetGovIdByGovernorateName/',
  ListDepartments: "http://localhost:24813/api/Department/ListDepartments",
  ListDepartmentsByHospitalId: "http://localhost:24813/api/Department/ListDepartmentsByHospitalId/",
  GetDepartmentsByHospitalId: "http://localhost:24813/api/Department/GetDepartmentsByHospitalId/",
  SortDepartments: "http://localhost:24813/api/Department/SortDepartments/",
  GetDepartmentById: "http://localhost:24813/api/Department/GetById/",
  AddDepartment: "http://localhost:24813/api/Department/AddDepartment",
  AddDepartmentToHospital: "http://localhost:24813/api/Department/AddDepartmentToHospital",
  UpdateDepartment: "http://localhost:24813/api/Department/UpdateDepartment/",
  DeleteDepartment: "http://localhost:24813/api/Department/DeleteDepartment/",
  GetDepartmentWithPaging: "http://localhost:24813/api/Department/GetDepartmentsWithPaging/",
  getDepartmentcount: "http://localhost:24813/api/Department/getcount",
  ListHospitals: "http://localhost:24813/api/Hospital/ListHospitals",
  CountDepartments: "http://localhost:24813/api/Hospital/CountDepartments/",
  CountHospitals: "http://localhost:24813/api/Hospital/CountHospitals",
  GetTop10Hospitals: "http://localhost:24813/api/Hospital/GetTop10Hospitals/",
  AddHospital: "http://localhost:24813/api/Hospital/AddHospital",
  GetHospitalById: "http://localhost:24813/api/Hospital/GetById/",
  GetHospitalDetailById: "http://localhost:24813/api/Hospital/GetHospitalDetailById/",
  GetHospitalsByUserId: "http://localhost:24813/api/Hospital/GetHospitalsByUserId/",
  GetHospitalsByUserIdAndPaging: "http://localhost:24813/api/Hospital/GetHospitalsByUserIdAndPaging/",
  GetHospitalsByUserIdAndPagingCount: "http://localhost:24813/api/Hospital/GetHospitalsByUserIdAndPagingCount/",
  GetHospitalsByCityId: "http://localhost:24813/api/Hospital/GetHospitalsByCityId/",
  GetHospitalsBySubOrganizationId: "http://localhost:24813/api/Hospital/GetHospitalsBySubOrganizationId/",
  GetHospitalsByGovCityOrgSubOrgId: "http://localhost:24813/api/Hospital/GetHospitalsByGovCityOrgSubOrgId/",



  
  GetHospitalDepartmentByHospitalId: "http://localhost:24813/api/Hospital/GetHospitalDepartmentByHospitalId/",
  GetHospitalDepartmentByHospitalId2: "http://localhost:24813/api/Hospital/GetHospitalDepartmentByHospitalId2/",
  GetSelectedHospitalDepartmentByDepartmentId: "http://localhost:24813/api/Hospital/GetSelectedHospitalDepartmentByDepartmentId/",
  getHospitalcount: 'http://localhost:24813/api/Hospital/getcount',
  getHospitalWithPaging: 'http://localhost:24813/api/Hospital/GetAllWithPaging',
  CountHospitalsByCities: "http://localhost:24813/api/Hospital/CountHospitalsByCities",
  GetSubOrganizationsByHospitalId: "http://localhost:24813/api/Hospital/GetSubOrganizationsByHospitalId/",
  UpdateHospital: "http://localhost:24813/api/Hospital/UpdateHospital",
  UpdateHospitalDepartment: "http://localhost:24813/api/Hospital/UpdateHospitalDepartment",
  DeleteHospital: "http://localhost:24813/api/Hospital/DeleteHospital/",
  getHosByCityId: 'http://localhost:24813/api/Hospital/GetHospitalsByCityId/',
  SearchHospitals: "http://localhost:24813/api/Hospital/SearchInHospitals/",
  SearchHospitalsCount: "http://localhost:24813/api/Hospital/SearchInHospitalsCount",
  sortHospitals: 'http://localhost:24813/api/Hospital/SortHospitals/',
  sortHospitalAsset: 'http://localhost:24813/api/Hospital/SortHospitalAssets/',
  getHospitalWithAssets: 'http://localhost:24813/api/Hospital/GetHospitalsWithAssets/',
  ListUsers: "http://localhost:24813/api/User/ListUsers",
  ListUsersByHospitalId: "http://localhost:24813/api/User/ListUsersByHospitalId/",
  ListUsersInHospitalByEngRoleName: "http://localhost:24813/api/User/ListUsersInHospitalByEngRoleName/",
  ListUsersInHospitalByEngManagerRoleName: "http://localhost:24813/api/User/ListUsersInHospitalByEngManagerRoleName/",
  ListUsersWithPaging: 'http://localhost:24813/api/User/ListUsersWithPaging',
  SortUsers: 'http://localhost:24813/api/User/SortUsers/',
  getUsercount: 'http://localhost:24813/api/User/getcount',
  AddUser: "http://localhost:24813/api/User/AddUser",
  GetUserById: "http://localhost:24813/api/User/GetById/",
  UpdateUser: "http://localhost:24813/api/User/UpdateUser",
  DeleteUser: "http://localhost:24813/api/User/DeleteUser/",
  Login: "http://localhost:24813/api/Authenticate/Login",
  ListSuppliers: "http://localhost:24813/api/Supplier/ListSuppliers",
  FindSupplier: "http://localhost:24813/api/Supplier/FindSupplier/",
  FindSupplierByText: "http://localhost:24813/api/Supplier/FindSupplierByText/",
  GetTop10Suppliers: "http://localhost:24813/api/Supplier/GetTop10Suppliers/",
  GetTop10SuppliersCount: "http://localhost:24813/api/Supplier/GetTop10SuppliersCount/",
  CountSuppliers: "http://localhost:24813/api/Supplier/CountSuppliers",
  AddSupplier: "http://localhost:24813/api/Supplier/AddSupplier",
  GetSupplierById: "http://localhost:24813/api/Supplier/GetById/",
  UpdateSupplier: "http://localhost:24813/api/Supplier/UpdateSupplier",
  DeleteSupplier: "http://localhost:24813/api/Supplier/DeleteSupplier/",
  DeleteSupplierAttachment: "http://localhost:24813/api/Supplier/DeleteSupplierAttachment/",

  GetSupplierWithPaging: "http://localhost:24813/api/Supplier/GetSuppliersWithPaging",
  GetAllSuppliersWithPaging: "http://localhost:24813/api/Supplier/GetAllSuppliersWithPaging/",
  CreateSupplierAttachment: "http://localhost:24813/api/Supplier/CreateSupplierAttachment/",
  GetSupplierAttachmentsBySupplierId: "http://localhost:24813/api/Supplier/GetSupplierAttachmentsBySupplierId/",
  getSuppliercount: "http://localhost:24813/api/Supplier/getcount",
  CreateSupplierPDF: "http://localhost:24813/api/Supplier/CreateSupplierPDF/",
  CreateSelectedSupplierPDF: "http://localhost:24813/api/Supplier/CreateSelectedSupplierPDF/",


  GenerateWordForAllSupplier: "http://localhost:24813/api/Supplier/GenerateWordForAllSupplier/",
  GenerateWordForSelectedSupplier: "http://localhost:24813/api/Supplier/GenerateWordForSelectedSupplier/",

  GetLastDocumentForSupplierId: "http://localhost:24813/api/Supplier/GetLastDocumentForSupplierId/",

  SortSuppliers: "http://localhost:24813/api/Supplier/SortSuppliers/",
  ListCommetieeMembers: "http://localhost:24813/api/CommetieeMember/ListCommetieeMembers",
  CountCommetieeMembers: "http://localhost:24813/api/CommetieeMember/CountCommetieeMembers",
  AddCommetieeMember: "http://localhost:24813/api/CommetieeMember/AddCommetieeMember",
  GetCommetieeMemberById: "http://localhost:24813/api/CommetieeMember/GetById/",
  UpdateCommetieeMember: "http://localhost:24813/api/CommetieeMember/UpdateCommetieeMember",
  DeleteCommetieeMember: "http://localhost:24813/api/CommetieeMember/DeleteCommetieeMember/",
  ListCategoryTypes: "http://localhost:24813/api/CategoryType/ListCategoryTypes",
  AddCategoryType: "http://localhost:24813/api/CategoryType/AddCategoryType/",
  GetCategoryTypeById: "http://localhost:24813/api/CategoryType/GetById/",
  UpdateCategoryType: "http://localhost:24813/api/CategoryType/UpdateCategoryType/",
  DeleteCategoryType: "http://localhost:24813/api/CategoryType/DeleteCategoryType/",
  ListCategories: "http://localhost:24813/api/Category/ListCategories",
  AddCategory: "http://localhost:24813/api/Category/AddCategory/",
  GetCategoryById: "http://localhost:24813/api/Category/GetById/",
  GetCategoryByCategoryTypeId: "http://localhost:24813/api/Category/GetCategoryByCategoryTypeId/",
  UpdateCategory: "http://localhost:24813/api/Category/UpdateCategory/",
  DeleteCategory: "http://localhost:24813/api/Category/DeleteCategory/",
  GetCategorysWithPaging: "http://localhost:24813/api/Category/GetCategoriesWithPaging/",
  getCategorysCount: "http://localhost:24813/api/Category/getcount/",
  ListSubCategories: "http://localhost:24813/api/SubCategory/ListSubCategories",
  GetSubCategoryByCategoryId: "http://localhost:24813/api/SubCategory/GetSubCategoryByCategoryId/",
  AddSubCategory: "http://localhost:24813/api/SubCategory/AddSubCategory/",
  GetSubCategoryById: "http://localhost:24813/api/SubCategory/GetById/",
  UpdateSubCategory: "http://localhost:24813/api/SubCategory/UpdateSubCategory/",
  DeleteSubCategory: "http://localhost:24813/api/SubCategory/DeleteSubCategory/",
  GetSubCategorysWithPaging: "http://localhost:24813/api/SubCategory/GetSubCategoriesWithPaging/",
  getSubCategorysCount: "http://localhost:24813/api/SubCategory/getcount/",
  ListOrigins: "http://localhost:24813/api/Origin/ListOrigins",
  AddOrigin: "http://localhost:24813/api/Origin/AddOrigin/",
  GetOriginById: "http://localhost:24813/api/Origin/GetById/",
  UpdateOrigin: "http://localhost:24813/api/Origin/UpdateOrigin/",
  DeleteOrigin: "http://localhost:24813/api/Origin/DeleteOrigin/",
  GetOriginsWithPaging: 'http://localhost:24813/api/Origin/GetOriginsWithPaging/',
  getOriginscount: 'http://localhost:24813/api/Origin/getcount',
  SortOrigins: 'http://localhost:24813/api/Origin/SortOrigins/',
  CreateOriginPDF: 'http://localhost:24813/api/Origin/CreateOriginPDF/',

  ListBrands: "http://localhost:24813/api/Brand/ListBrands",
  ListAllBrands: "http://localhost:24813/api/Brand/ListAllBrands/",


  CountBrands: "http://localhost:24813/api/Brand/CountBrands",
  GetTop10Brands: "http://localhost:24813/api/Brand/GetTop10Brands/",

  GetBrandById: "http://localhost:24813/api/Brand/GetById/",
  AddBrand: "http://localhost:24813/api/Brand/AddBrand",
  UpdateBrand: "http://localhost:24813/api/Brand/UpdateBrand/",
  DeleteBrand: "http://localhost:24813/api/Brand/DeleteBrand/",
  GetBrandsWithPaging: "http://localhost:24813/api/Brand/GetBrandsWithPaging/",
  SortBrands: "http://localhost:24813/api/Brand/SortBrands/",
  getBrandsCount: "http://localhost:24813/api/Brand/getcount/",
  CreateBrandPDF: "http://localhost:24813/api/Brand/CreateBrandPDF/",

  ListAssetPeriorities: "http://localhost:24813/api/AssetPeriority/ListAssetPeriorities",
  ListAssetPerioritiesByHospitalId: "http://localhost:24813/api/AssetPeriority/ListAssetPerioritiesByHospitalId/",

  ListClassifications: "http://localhost:24813/api/Classification/ListClassifications",
  AddClassification: "http://localhost:24813/api/Classification/AddClassification/",
  GetClassificationById: "http://localhost:24813/api/Classification/GetById/",
  UpdateClassification: "http://localhost:24813/api/Classification/UpdateClassification/",
  DeleteClassification: "http://localhost:24813/api/Classification/DeleteClassification/",
  GetClassificationsWithPaging: "http://localhost:24813/api/Classification/GetClassificationsWithPaging/",
  getClassificationsCount: "http://localhost:24813/api/Classification/getcount/",
  SortClassifications: "http://localhost:24813/api/Classification/SortClassifications/",
  ListAllMasterAssets: "http://localhost:24813/api/MasterAsset/GetListMasterAsset",
  GenerateMasterAssetcode: "http://localhost:24813/api/MasterAsset/GenerateMasterAssetcode",
  GetTop10MasterAsset: "http://localhost:24813/api/MasterAsset/GetTop10MasterAsset/",
  getMasterAssetWithPaging: "http://localhost:24813/api/MasterAsset/GetMasterAssetsWithPaging",
  GetMasterAssetsWithPagingAndOrder: "http://localhost:24813/api/MasterAsset/GetMasterAssetsWithPagingAndOrder",
  getMasterAssetCount: "http://localhost:24813/api/MasterAsset/getcount",
  ListMasterAssetsByHospitalId: "http://localhost:24813/api/MasterAsset/ListMasterAssetsByHospitalId/",
  DeleteMasterAssetImage: "http://localhost:24813/api/MasterAsset/DeleteMasterAssetImage/",
  ListMasterAssetsByHospitalUserId: "http://localhost:24813/api/MasterAsset/ListMasterAssetsByHospitalUserId/",
  GetListMasterAsset: "http://localhost:24813/api/MasterAsset/ListMasterAssets/",
  GetMasterAssetById: "http://localhost:24813/api/MasterAsset/GetById/",
  AutoCompleteMasterAssetName: "http://localhost:24813/api/MasterAsset/AutoCompleteMasterAssetName/",

  AutoCompleteMasterAssetName2: "http://localhost:24813/api/MasterAsset/AutoCompleteMasterAssetName2/",
  AutoCompleteMasterAssetName3: "http://localhost:24813/api/MasterAsset/AutoCompleteMasterAssetName3/",
  DistinctAutoCompleteMasterAssetName: "http://localhost:24813/api/MasterAsset/DistinctAutoCompleteMasterAssetName/",

  GetDistintMasterAssetModels: "http://localhost:24813/api/MasterAsset/GetDistintMasterAssetModels/",

  GetDistintMasterAssetBrands: "http://localhost:24813/api/MasterAsset/GetDistintMasterAssetBrands/",

  
  ViewMasterAssetById: "http://localhost:24813/api/MasterAsset/ViewMasterAsset/",
  CountMasterAssets: "http://localhost:24813/api/MasterAsset/CountMasterAssets",
  GetTop10MasterAssetCount: "http://localhost:24813/api/MasterAsset/GetTop10MasterAssetCount/",
  CountMasterAssetsByBrand: "http://localhost:24813/api/MasterAsset/CountMasterAssetsByBrand/",
  CountMasterAssetsBySupplier: "http://localhost:24813/api/MasterAsset/CountMasterAssetsBySupplier/",
  SearchInMasterAssets: "http://localhost:24813/api/MasterAsset/SearchInMasterAssets/",
  SearchInMasterAssetsCount: "http://localhost:24813/api/MasterAsset/SearchInMasterAssetsCount",
  SortMasterAssets: "http://localhost:24813/api/MasterAsset/SortMasterAssets/",
  UpdateMasterAsset: "http://localhost:24813/api/MasterAsset/UpdateMasterAsset",
  UpdateMasterAssetImageAfterInsert: "http://localhost:24813/api/MasterAsset/UpdateMasterAssetImageAfterInsert",
  AddMasterAsset: "http://localhost:24813/api/MasterAsset/AddMasterAsset",
  DeleteMasterAsset: "http://localhost:24813/api/MasterAsset/DeleteMasterAsset/",
  CreateMasterAssetAttachments: "http://localhost:24813/api/MasterAsset/CreateMasterAssetAttachments",
  GetAttachmentByMasterAssetId: "http://localhost:24813/api/MasterAsset/GetAttachmentByMasterAssetId/",
  DeleteMasterAssetAttachmentById: "http://localhost:24813/api/MasterAsset/DeleteMasterAssetAttachment/",
  GetAssetHospitalId: "http://localhost:24813/api/HospitalApplication/GetAssetHospitalId/",



  UpdateQrCode: "http://localhost:24813/api/Qr/UpdateQrCode/",
  UpdateSelectedQrCode: "http://localhost:24813/api/Qr/UpdateSelectedQrCode",
  GenerateWordForPoliceSelectedQrCode: "http://localhost:24813/api/Qr/GenerateWordForPoliceSelectedQrCode",
  GenerateWordForHospitalSelectedQrCode: "http://localhost:24813/api/Qr/GenerateWordForHospitalSelectedQrCode",
  GenerateWordForUniversitySelectedQrCode: "http://localhost:24813/api/Qr/GenerateWordForUniversitySelectedQrCode",


  GetAllAssetsTimes: "http://localhost:24813/api/WNAssetTimes/GetAllAssetsTimes/",
  GetAllForCalendar: "http://localhost:24813/api/WNAssetTimes/GetAllForCalendar/",
  CreateAssetTimes: "http://localhost:24813/api/WNAssetTimes/CreateAssetTimes/",
  GetWNPMAssetTimeAttachmentByWNPMAssetTimeId: "http://localhost:24813/api/WNAssetTimes/GetWNPMAssetTimeAttachmentByWNPMAssetTimeId/",
  CreateWNPMAssetTimeAttachment: "http://localhost:24813/api/WNAssetTimes/CreateWNPMAssetTimeAttachment",
  GetWNAssetTimeById: "http://localhost:24813/api/WNAssetTimes/GetWNAssetTimeById/",
  UpdateWNAssetTime: "http://localhost:24813/api/WNAssetTimes/UpdateWNAssetTime",
  SearchAssetTimes: "http://localhost:24813/api/WNAssetTimes/SearchAssetTimes/",
  SortAssetTimes: "http://localhost:24813/api/WNAssetTimes/SortAssetTimes/",
  GetAllAssetTimesIsDone: "http://localhost:24813/api/WNAssetTimes/GetAllAssetTimesIsDone/",
  GetYearQuarters: "http://localhost:24813/api/WNAssetTimes/GetYearQuarters",
  GetAssetTimeById: "http://localhost:24813/api/WNAssetTimes/GetAssetTimeById/",

  ListAssetMovements: "http://localhost:24813/api/AssetMovement/ListAssetMovements/",

  GetAssetMovements: "http://localhost:24813/api/AssetMovement/GetAssetMovements/",

  AddAssetMovement: "http://localhost:24813/api/AssetMovement/AddAssetMovement",
  GetAssetMovementById: "http://localhost:24813/api/AssetMovement/GetById/",
  UpdateAssetMovement: "http://localhost:24813/api/AssetMovement/UpdateAssetMovement",
  DeleteAssetMovement: "http://localhost:24813/api/AssetMovement/DeleteAssetMovement/",
  GetMovementByAssetDetailId: "http://localhost:24813/api/AssetMovement/GetMovementByAssetDetailId/",
  ListExternalAssetMovements: "http://localhost:24813/api/ExternalAssetMovement/ListExternalAssetMovements/",
  AddExternalAssetMovement: "http://localhost:24813/api/ExternalAssetMovement/AddExternalAssetMovement",
  CreateExternalAssetMovementAttachments: "http://localhost:24813/api/ExternalAssetMovement/CreateExternalAssetMovementAttachments/",
  GetExternalMovementAttachmentByExternalAssetMovementId: "http://localhost:24813/api/ExternalAssetMovement/GetExternalMovementAttachmentByExternalAssetMovementId/",
  GetExternalAssetMovementByAssetDetailId: "http://localhost:24813/api/ExternalAssetMovement/GetExternalMovementsByAssetDetailId/",

  GetExternalAssetMovementById: "http://localhost:24813/api/ExternalAssetMovement/GetExternalAssetMovementById/",
  ListECRIs: "http://localhost:24813/api/ECRI/ListECRIs",
  AddECRI: "http://localhost:24813/api/ECRI/AddECRI",
  GetECRIById: "http://localhost:24813/api/ECRI/GetById/",
  UpdateECRI: "http://localhost:24813/api/ECRI/UpdateECRI",
  DeleteECRI: "http://localhost:24813/api/ECRI/DeleteECRI/",
  GetECRISWithPaging: "http://localhost:24813/api/ECRI/GetECRISWithPaging/",
  getECRIScount: "http://localhost:24813/api/ECRI/getcount",
  SortECRI: "http://localhost:24813/api/ECRI/SortECRI/",
  ListAssetStatus: "http://localhost:24813/api/AssetStatus/ListAssetStatus",
  GetAssetStatusWithPaging: "http://localhost:24813/api/AssetStatus/GetAssetStatusWithPaging",
  GetAssetStatusCount: "http://localhost:24813/api/AssetStatus/GetAssetStatusCount",
  GetStatusTransactionByAssetDetailId: "http://localhost:24813/api/AssetStatusTransaction/GetStatusTransactionByAssetDetailId/",
  GetLastTransactionByAssetId: "http://localhost:24813/api/AssetStatusTransaction/GetLastTransactionByAssetId/",
  AddAssetStatusTransaction: "http://localhost:24813/api/AssetStatusTransaction/AddAssetStatusTransaction",
  DeleteAssetStatusTransaction: "http://localhost:24813/api/AssetStatusTransaction/DeleteAssetStatusTransaction/",
  getAssetStatusById: "http://localhost:24813/api/AssetStatus/GetById/",
  AddAssetStatus: "http://localhost:24813/api/AssetStatus/AddAssetStatus",
  UpdateAssetStatus: "http://localhost:24813/api/AssetStatus/UpdateAssetStatus/",
  DeleteAssetStatus: "http://localhost:24813/api/AssetStatus/DeleteAssetStatus/",
  SortAssetStatuses: "http://localhost:24813/api/AssetStatus/SortAssetStatuses/",

  GetHospitalAssetStatus: "http://localhost:24813/api/AssetStatus/GetHospitalAssetStatus/",

  CreateAssetStatusPDF: "http://localhost:24813/api/AssetStatus/CreateAssetStatusPDF/",
  ListMasterContracts: "http://localhost:24813/api/Contract/ListMasterContracts",
  GetMasterContractById: "http://localhost:24813/api/Contract/GetById/",
  GetContractsByMasterContractId: "http://localhost:24813/api/Contract/GetContractsByMasterContractId/",
  GetListofHospitalsFromAssetContractDetailByMasterContractId: "http://localhost:24813/api/Contract/GetListofHospitalsFromAssetContractDetailByMasterContractId/",
  GetContractAssetsByHospitalId: "http://localhost:24813/api/Contract/GetContractAssetsByHospitalId/",
  GetContractByHospitalId: "http://localhost:24813/api/Contract/GetContractByHospitalId/",
  GetListBoxMasterContractsByHospitalId: "http://localhost:24813/api/Contract/GetListBoxMasterContractsByHospitalId/",
  GetMasterContracts: "http://localhost:24813/api/Contract/ListMasterContracts/",
  getContractcount: "http://localhost:24813/api/Contract/getcount/",
  SearchInContract: "http://localhost:24813/api/Contract/SearchInContract/",
  SearchInContractCount: "http://localhost:24813/api/Contract/SearchInContractCount/",
  UpdateMasterContract: "http://localhost:24813/api/Contract/UpdateMasterContract",
  AddMasterContract: "http://localhost:24813/api/Contract/AddMasterContract",
  DeleteMasterContract: "http://localhost:24813/api/Contract/DeleteMasterContract/",
  AddContract: "http://localhost:24813/api/Contract/AddContract",
  DeleteContract: "http://localhost:24813/api/Contract/DeleteContract/",
  SortContracts: "http://localhost:24813/api/Contract/SortContracts/",

  // Asset Detail Url 
  ListAssets: "http://localhost:24813/api/AssetDetail/ListAssetDetails",
  GenerateAssetDetailBarcode: "http://localhost:24813/api/AssetDetail/GenerateAssetDetailBarcode",
  GetAssetsByAgeGroup: "http://localhost:24813/api/AssetDetail/GetAssetsByAgeGroup/",
  GetGeneralAssetsByAgeGroup: "http://localhost:24813/api/AssetDetail/GetGeneralAssetsByAgeGroup/",
  ListAssetDetailCarouselByUserId: "http://localhost:24813/api/AssetDetail/ListAssetDetailCarouselByUserId/",
  GetHospitalAssets: "http://localhost:24813/api/AssetDetail/GetHospitalAssets/",
  GetAllAssets: 'http://localhost:24813/api/AssetDetail/ListAssetDetails',
  getHospitalAssetWithPaging: "http://localhost:24813/api/AssetDetail/ListAssetDetailsWithPaging",
  CountAssetsByHospital: "http://localhost:24813/api/AssetDetail/CountAssetsByHospital",
  CountAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/CountAssetsByHospitalId/",
  ListTopAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/ListTopAssetsByHospitalId/",
  ListAssetsByGovernorateIds: "http://localhost:24813/api/AssetDetail/ListAssetsByGovernorateIds",
  ListAssetsByCityIds: "http://localhost:24813/api/AssetDetail/ListAssetsByCityIds",
  CountAssetsInHospitalByHospitalId: "http://localhost:24813/api/AssetDetail/CountAssetsInHospitalByHospitalId/",
  FilterDataByDepartmentBrandSupplierId: 'http://localhost:24813/api/AssetDetail/FilterDataByDepartmentBrandSupplierId',
  FilterData: 'http://localhost:24813/api/AssetDetail/FilterAsset/',
  PrintAssetHistory: "http://localhost:24813/api/AssetDetail/PrintAssetHistory/",

  GetAssetNameByMasterAssetIdAndHospitalId: "http://localhost:24813/api/AssetDetail/GetAssetNameByMasterAssetIdAndHospitalId/",

  GetAllAssetDetailsByHospitalId: "http://localhost:24813/api/AssetDetail/GetAllAssetDetailsByHospitalId/",
  AutoCompleteAssetBarCode: "http://localhost:24813/api/AssetDetail/AutoCompleteAssetBarCode/",
  AutoCompleteAssetBarCodeByDepartmentId: "http://localhost:24813/api/AssetDetail/AutoCompleteAssetBarCodeByDepartmentId/",
  GetAutoCompleteSupplierNoneExcludedAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/GetAutoCompleteSupplierNoneExcludedAssetsByHospitalId/",
  GetAutoCompleteSupplierExcludedAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/GetAutoCompleteSupplierExcludedAssetsByHospitalId/",
  AutoCompleteAssetSerial: "http://localhost:24813/api/AssetDetail/AutoCompleteAssetSerial/",
  ExportAssetsByStatusId: "http://localhost:24813/api/AssetDetail/ExportAssetsByStatusId/",
  GetAllAssetsByStatusId: "http://localhost:24813/api/AssetDetail/GetAllAssetsByStatusId/",
  GetAllAssetsCountByStatusId: "http://localhost:24813/api/AssetDetail/GetAllAssetsCountByStatusId/",
  GetAssetById: "http://localhost:24813/api/AssetDetail/GetById/",
  ViewAssetDetailByMasterId: "http://localhost:24813/api/AssetDetail/ViewAssetDetailByMasterId/",
  ViewAllAssetDetailByMasterId: "http://localhost:24813/api/AssetDetail/ViewAllAssetDetailByMasterId/",
  GetListOfAssetDetailsByHospitalId: "http://localhost:24813/api/AssetDetail/GetListOfAssetDetailsByHospitalId/",
  GetNoneExcludedAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/GetNoneExcludedAssetsByHospitalId/",
  GetSupplierNoneExcludedAssetsByHospitalId: "http://localhost:24813/api/AssetDetail/GetSupplierNoneExcludedAssetsByHospitalId/",
  GetListOfAssetDetailsByHospitalNotInContract: "http://localhost:24813/api/AssetDetail/GetListOfAssetDetailsByHospitalNotInContract/",
  GetListOfAssetDetailsByHospitalNotInContract2: "http://localhost:24813/api/AssetDetail/GetListOfAssetDetailsByHospitalNotInContract2/",
  GetListOfAssetDetailsByHospitalNotInContractBySerialNumber: "http://localhost:24813/api/AssetDetail/GetListOfAssetDetailsByHospitalNotInContractBySerialNumber/",
  AlertAssetsWarrantyEndBefore3Monthes: "http://localhost:24813/api/AssetDetail/AlertAssetsWarrantyEndBefore3Monthes/",
  SearchHospitalAssetsByDepartmentId: "http://localhost:24813/api/AssetDetail/SearchHospitalAssetsByDepartmentId/",
  GetAssetHistoryById: "http://localhost:24813/api/AssetDetail/GetAssetHistoryById/",
  CreateAssetDepartmentBrandSupplierPDF: "http://localhost:24813/api/AssetDetail/CreateAssetDepartmentBrandSupplierPDF/",
  getAssetDetailcount: "http://localhost:24813/api/AssetDetail/getcount",
  GetAssetDetailsByAssetId: "http://localhost:24813/api/AssetDetail/GetAssetDetailsByAssetId/",
  GetOwnersByAssetDetailId: "http://localhost:24813/api/AssetDetail/GetOwnersByAssetDetailId/",
  GetAllPMAssetTaskSchedules: "http://localhost:24813/api/AssetDetail/GetAllPMAssetTaskSchedules/",
  GetAllPMAssetTaskScheduleByAssetId: "http://localhost:24813/api/AssetDetail/GetAllPMAssetTaskScheduleByAssetId/",
  CreateAssetDetailAttachments: "http://localhost:24813/api/AssetDetail/CreateAssetDetailAttachments",
  GetAttachmentByAssetDetailId: "http://localhost:24813/api/AssetDetail/GetAttachmentByAssetDetailId/",
  DeleteAssetDetailAttachment: "http://localhost:24813/api/AssetDetail/DeleteAssetDetailAttachment/",
  GetLastDocumentForAssetDetailId: 'http://localhost:24813/api/AssetDetail/GetLastDocumentForAssetDetailId/',
  SortHospitalAssetsBySupplierId: 'http://localhost:24813/api/AssetDetail/SortHospitalAssetsBySupplierId/',
  UpdateAsset: "http://localhost:24813/api/AssetDetail/UpdateAssetDetail",
  AddAsset: "http://localhost:24813/api/AssetDetail/AddAssetDetail",

  GetRequestsForAssetId: "http://localhost:24813/api/AssetDetail/GetRequestsForAssetId/",
  DeleteAsset: "http://localhost:24813/api/AssetDetail/DeleteAssetDetail/",
  SearchAssetDetails: "http://localhost:24813/api/AssetDetail/SearchAssetDetails/",
  GenerateQrCodeForAllAssets: "http://localhost:24813/api/AssetDetail/GenerateQrCodeForAllAssets",
  DownloadQRWordFile: "http://localhost:24813/api/AssetDetail/DownloadQRWordFile",
  GenerateWordForQrCodeForPoliceAssets: "http://localhost:24813/api/AssetDetail/GenerateWordForQrCodeForPoliceAssets",
  GenerateWordForQrCodeForUniversityAssets: "http://localhost:24813/api/AssetDetail/GenerateWordForQrCodeForUniversityAssets",
  GenerateWordForQrCodeForHospitalAssets: "http://localhost:24813/api/AssetDetail/GenerateWordForQrCodeForHospitalAssets",
  getAssetByBrand: 'http://localhost:24813/api/AssetDetail/GetAssetByBrands/',
  getAssetByHospital: 'http://localhost:24813/api/AssetDetail/GetAssetByHospital/',
  getAssetByGovernorate: 'http://localhost:24813/api/AssetDetail/GetAssetByGovernorate/',
  getAssetByCity: 'http://localhost:24813/api/AssetDetail/GetAssetByCity/',
  getAssetBySupplier: 'http://localhost:24813/api/AssetDetail/GetAssetBySupplier/',
  getAssetByDepartment: 'http://localhost:24813/api/AssetDetail/GetAssetByDepartment/',
  getAssetByOrganization: 'http://localhost:24813/api/AssetDetail/GetAssetByOrganization/',
  SearchAssetDetailsCount: "http://localhost:24813/api/AssetDetail/SearchAssetDetailsCount",
  SearchAssetDetailsByHospitalId: "http://localhost:24813/api/AssetDetail/SearchAssetDetailsByHospitalId",
  GetAssetsyUserId: 'http://localhost:24813/api/AssetDetail/GetAssetsByUserId/',

  GeoSortAssetsWithoutSearch: "http://localhost:24813/api/AssetDetail/GeoSortAssetsWithoutSearch/",

  GenericReportGetAssetsByUserIdAndPaging: 'http://localhost:24813/api/AssetDetail/GenericReportGetAssetsByUserIdAndPaging/',
  GetAssetDetailsByUserIdwithPaging: "http://localhost:24813/api/AssetDetail/GetAssetDetailsByUserIdWithPaging/",
  GetAssetDetailsByUserIdWithPaging2: "http://localhost:24813/api/AssetDetail/GetAssetDetailsByUserIdWithPaging2/",
  GetHospitalAssetsBySupplierId: "http://localhost:24813/api/AssetDetail/GetHospitalAssetsBySupplierId/",
  SearchHospitalAssetsBySupplierId: "http://localhost:24813/api/AssetDetail/SearchHospitalAssetsBySupplierId/",
  GetHospitalAssetsByGovIdAndDeptIdAndHospitalId2: "http://localhost:24813/api/AssetDetail/GetHospitalAssetsByGovIdAndDeptIdAndHospitalId/",

  GetAllwithgrouping: 'http://localhost:24813/api/AssetDetail/group/',
  FilterDataByDepartmentBrandSupplierIdAndPaging: "http://localhost:24813/api/AssetDetail/FilterDataByDepartmentBrandSupplierIdAndPaging",
  GetAssetsByBrandId: "http://localhost:24813/api/AssetDetail/GetAssetsByBrandId",
  GetAssetsByDepartmentId: "http://localhost:24813/api/AssetDetail/GetAssetsByDepartmentId",
  GetAssetsBySupplierId: "http://localhost:24813/api/AssetDetail/GetAssetsBySupplierId",
  GetAssetsBySupplierIdWithPaging: "http://localhost:24813/api/AssetDetail/GetAssetsBySupplierIdWithPaging",
  GetAssetsByGovernorateIdWithPaging: "http://localhost:24813/api/AssetDetail/GetAssetsByGovernorateIdWithPaging",

  GetAssetsByCityIdWithPaging: "http://localhost:24813/api/AssetDetail/GetAssetsByCityIdWithPaging",
  GetAssetsByHospitalIdWithPaging: "http://localhost:24813/api/AssetDetail/GetAssetsByHospitalIdWithPaging",
  
  SortAssetDetail: "http://localhost:24813/api/AssetDetail/SortAssetDetail",
  SortAssetDetailAfterSearch: "http://localhost:24813/api/AssetDetail/SortAssetDetailAfterSearch",
  GroupAssetDetailsByBrand: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsByBrand",
  GroupAssetDetailsBySupplier: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsBySupplier",
  GroupAssetDetailsByDepartment: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsByDepartment",
  GroupAssetDetailsByGovernorate: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsByGovernorate",
  GroupAssetDetailsByCity: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsByCity",
  GroupAssetDetailsByHospital: "http://localhost:24813/api/AssetDetail/GroupAssetDetailsByHospital",
  SortAndFilterHospitalAssets: "http://localhost:24813/api/AssetDetail/SortAndFilterHospitalAssets/",
  ListHospitalAssets: "http://localhost:24813/api/AssetDetail/ListHospitalAssets/",
  GetAllWithDate: "http://localhost:24813/api/WNAssetTimes/GetAllWithDate/",


  ///Request URLs
  requests: 'http://localhost:24813/api/Request/',
  GenerateRequestNumber: 'http://localhost:24813/api/Request/GenerateRequestNumber',
  PrintServiceRequestById: "http://localhost:24813/api/Request/PrintServiceRequestById/",
  ListRequests: "http://localhost:24813/api/Request/ListRequests/",
  UpdateRequest: 'http://localhost:24813/api/Request/UpdateRequest',
  GetByRequestCode: 'http://localhost:24813/api/Request/GetByRequestCode/',
  GetRequestById: 'http://localhost:24813/api/Request/GetById/',
  DeleteRequest: 'http://localhost:24813/api/Request/DeleteRequest/',
  GetRequestByWorkOrderId: 'http://localhost:24813/api/Request/GetRequestByWorkOrderId/',
  GetAllRequestsWithTracking: 'http://localhost:24813/api/Request/GetAllRequestsWithTracking',
  sortRequests: 'http://localhost:24813/api/Request/SortRequests/',
  sortRequestsByPaging: 'http://localhost:24813/api/Request/SortRequestsByPaging/',
  SortRequestsByAssetId: 'http://localhost:24813/api/Request/SortRequestsByAssetId/',
  GetRequestsByUserIdWithPagingAndStatusIdAndAssetId: 'http://localhost:24813/api/Request/GetRequestsByUserIdWithPagingAndStatusIdAndAssetId/',
  GetRequestsByUserIdWithPagingAndStatusIdAndAssetIdCount: 'http://localhost:24813/api/Request/GetRequestsByUserIdWithPagingAndStatusIdAndAssetIdCount',
  CountAllRequestsByAssetId: 'http://localhost:24813/api/Request/CountAllRequestsByAssetId/',
  CountRequestsByHospitalId: 'http://localhost:24813/api/Request/CountRequestsByHospitalId/',
  CreateRequestAttachments: 'http://localhost:24813/api/Request/CreateRequestAttachments/',
  GetAllRequestsWithTrackingByUserId: 'http://localhost:24813/api/Request/GetAllRequestsWithTrackingByUserId/',
  GetAllRequestsWithTrackingByUserIdWithPaging: "http://localhost:24813/api/Request/GetAllRequestsWithTrackingByUserIdWithPaging/",

  GetOldRequestsByHospitalAssetId: "http://localhost:24813/api/Request/GetOldRequestsByHospitalAssetId/",


  getRequestscount: "http://localhost:24813/api/Request/getcount/",
  GetTotalOpenRequest: "http://localhost:24813/api/Request/GetTotalOpenRequest/",
  ListNewRequests: "http://localhost:24813/api/Request/ListNewRequests/",
  ListOpenRequests: "http://localhost:24813/api/Request/ListOpenRequests/",
  UpdateOpenedRequest: "http://localhost:24813/api/Request/UpdateOpenedRequest/",
  GetAllRequestEstimations: "http://localhost:24813/api/Request/GetAllRequestEstimations/",
  GetRequestEstimations: "http://localhost:24813/api/Request/GetRequestEstimations/",
  CreateServiceRequestPDF: "http://localhost:24813/api/Request/CreatePDF",
  CreateSRReportWithinDatePDF: "http://localhost:24813/api/Request/CreateSRReportWithinDatePDF",
  CreateSRReportWithinDateAndStatusPDF: "http://localhost:24813/api/Request/CreateSRReportWithinDateAndStatusPDF",
  CreateSRReportWithInProgressPDF: "http://localhost:24813/api/Request/CreateSRReportWithInProgressPDF",
  CountGetRequestEstimations: "http://localhost:24813/api/Request/CountGetRequestEstimations",
  ListOpenRequestTracks: "http://localhost:24813/api/Request/ListOpenRequestTracks/",
  UpdateOpenedRequestTrack: "http://localhost:24813/api/Request/UpdateOpenedRequestTrack/",
  GetRequestsByDate: "http://localhost:24813/api/Request/GetRequestsByDate/",
  GetAllRequestsByDate: "http://localhost:24813/api/Request/GetAllRequestsByDate",
  GetRequestsByDateAndStatus: "http://localhost:24813/api/Request/GetRequestsByDateAndStatus/",
  GetOpenRequestsByDate: "http://localhost:24813/api/Request/GetOpenRequestsByDate/",
  CreateOpenServiceRequestPDF: "http://localhost:24813/api/Request/CreateOpenServiceRequestPDF/",
  SearchInRequests: "http://localhost:24813/api/Request/SearchInRequests/",
  SearchInRequests2: "http://localhost:24813/api/Request/SearchInRequests2/",
  SearchInRequestsCount: "http://localhost:24813/api/Request/SearchInRequestsCount",
  GetAllRequestsWithTrackingByUserIdWithPagingAndStatusId: "http://localhost:24813/api/Request/GetAllRequestsWithTrackingByUserIdWithPagingAndStatusId/",
  ExportRequestsByStatusId: 'http://localhost:24813/api/Request/ExportRequestsByStatusId',
  AlertOpenedRequestAssetsAndHighPeriority: 'http://localhost:24813/api/Request/AlertOpenedRequestAssetsAndHighPeriority/',
  CreateServiceRequestListPDF: 'http://localhost:24813/api/Request/CreateServiceRequestPDF',
  CreateServiceRequestGeneratePDF: 'http://localhost:24813/api/Request/CreateServiceRequestGeneratePDF',
  GetRequestsByPageNumber: "http://localhost:24813/api/Request/GetRequestsByPageNumber",
  GetTotalRequestForAssetInHospital: "http://localhost:24813/api/Request/GetTotalRequestForAssetInHospital/",
  DownloadCreateSRReportWithinDatePDF: "http://localhost:24813/api/Request/DownloadCreateSRReportWithinDatePDF",
  DownloadSRReportWithInProgressPDF: "http://localhost:24813/api/Request/DownloadSRReportWithInProgressPDF",

  CreateContractAttachments: 'http://localhost:24813/api/Contract/CreateContractAttachments',
  CreateWOReportWithinDatePDF: "http://localhost:24813/api/WorkOrder/CreateWOReportWithinDatePDF",
  RequestPeriorities: 'http://localhost:24813/api/RequestPeriorities',
  RequestModes: 'http://localhost:24813/api/RequestModes',
  RequestDocument: 'http://localhost:24813/api/RequestDocument',
  AddRequestDocuments: 'http://localhost:24813/api/AddRequestDocuments',
  DeleteRequestDocument: 'http://localhost:24813/api/RequestDocument/DeleteRequestDocument/',
  GetRequestDocumentByRequestId: 'http://localhost:24813/api/RequestDocument/GetRequestDocumentByRequestId/',
  uploadImage: 'http://localhost:24813/api/RequestDocument/uploadimage/',
  RequestTracking: 'http://localhost:24813/api/RequestTracking',
  UpdateRequestTracking: 'http://localhost:24813/api/RequestTracking/UpdateRequestTracking',
  GetFirstTrackForRequestByRequestId: 'http://localhost:24813/api/RequestTracking/GetFirstTrackForRequestByRequestId/',
  AddRequestTracking: 'http://localhost:24813/api/RequestTracking/AddRequestTracking',
  GetAllRequestFromTrackingByuserId: 'http://localhost:24813/api/RequestTracking/GetAllRequestFromTrackingByuserId/',
  GetAllTrackingByRequestId: 'http://localhost:24813/api/RequestTracking/GetAllTrackingsByRequestId/',
  GetAllTracksByRequestId: 'http://localhost:24813/api/RequestTracking/GetAllTracksByRequestId/',
  CountRequestTracksByRequestId: 'http://localhost:24813/api/RequestTracking/CountRequestTracksByRequestId/',
  GetAttachmentsByWorkOrderId: 'http://localhost:24813/api/WorkOrderTracking/GetAttachmentsByWorkOrderId/',
  RequestStatus: 'http://localhost:24813/api/RequestStatus',
  GetAllForReport: 'http://localhost:24813/api/RequestStatus/GetAllForReport',
  GetAllForReportByDate: 'http://localhost:24813/api/RequestStatus/GetAllForReportByDate',
  GetAllRequestStatus: 'http://localhost:24813/api/RequestStatus/GetAll/',

  GetRequestStatusByUserId: 'http://localhost:24813/api/RequestStatus/GetRequestStatusByUserId/',

  GetAllByHospitalId: 'http://localhost:24813/api/RequestStatus/GetAllByHospitalId/',
  AddRequestStatus: "http://localhost:24813/api/RequestStatus/",
  GetRequestStatusById: "http://localhost:24813/api/RequestStatus/GetById/",
  UpdateRequestStatus: "http://localhost:24813/api/RequestStatus/",
  DeleteRequestStatus: "http://localhost:24813/api/RequestStatus/DeleteReqStatus/",
  UpdateRequestStatus2: "http://localhost:24813/api/RequestStatus/UpdateRequestStatus",
  GetRequestStatusesWithPaging: "http://localhost:24813/api/RequestStatus/GetRequestStatusesWithPaging",
  GetRequestStatusesCount: "http://localhost:24813/api/RequestStatus/GetCount",
  SortRequestStatuses: "http://localhost:24813/api/RequestStatus/SortRequestStatuses/",

  CreateRequestStatusPDF: "http://localhost:24813/api/RequestStatus/CreateRequestStatusPDF/",
  CreateRequestTypePDF: "http://localhost:24813/api/RequestType/CreateRequestTypePDF/",
  CreateWOStatusPDF: "http://localhost:24813/api/WorkOrderStatus/CreateWorkOrderStatusPDF/",
  CreateWOTypePDF: "http://localhost:24813/api/WorkOrderType/CreateWorkOrderTypePDF/",
  GetAllHospitalSupplierStatus: 'http://localhost:24813/api/HospitalSupplierStatus/GetAll/',
  GetHospitalSupplierStatus: 'http://localhost:24813/api/HospitalSupplierStatus/GetAll/',
  GetAllByHospitals: 'http://localhost:24813/api/HospitalSupplierStatus/GetAllByHospitals',
  GetHospitalSupplierStatusByStatusAppTypeId: 'http://localhost:24813/api/HospitalSupplierStatus/GetAllByStatusAppTypeId/',
  GetHospitalByStatusAppTypeId: 'http://localhost:24813/api/HospitalSupplierStatus/GetHospitalByStatusAppTypeId/',
  ListBuildings: "http://localhost:24813/api/Building/ListBuildings",
  AddBuilding: "http://localhost:24813/api/Building/AddBuilding",
  GetBuildingById: "http://localhost:24813/api/Building/GetById/",
  UpdateBuilding: "http://localhost:24813/api/Building/UpdateBuilding",
  DeleteBuilding: "http://localhost:24813/api/Building/DeleteBuilding/",
  GetAllBuildingsByHospitalId: "http://localhost:24813/api/Building/GetAllBuildingsByHospitalId/",
  ListFloors: "http://localhost:24813/api/Floor/ListFloors",
  AddFloor: "http://localhost:24813/api/Floor/AddFloor",
  GetFloorById: "http://localhost:24813/api/Floor/GetById/",
  UpdateFloor: "http://localhost:24813/api/Floor/UpdateFloor",
  DeleteFloor: "http://localhost:24813/api/Floor/DeleteFloor/",
  GetFloorsByBuildingId: "http://localhost:24813/api/Floor/GetAllFloorsBybuildingId/",
  ListRooms: "http://localhost:24813/api/Room/ListRooms",
  AddRoom: "http://localhost:24813/api/Room/AddRoom",
  GetRoomById: "http://localhost:24813/api/Room/GetById/",
  UpdateRoom: "http://localhost:24813/api/Room/UpdateRoom",
  DeleteRoom: "http://localhost:24813/api/Room/DeleteRoom/",
  GetRoomsByFloorId: "http://localhost:24813/api/Room/GetAllRoomsByFloorId/",
  ListEmployees: "http://localhost:24813/api/Employee/ListEmployees",
  ListEmployeesWithPaging: "http://localhost:24813/api/Employee/ListEmployeesWithPaging/",
  getEmployeescount: "http://localhost:24813/api/Employee/getcount/",
  AddEmployee: "http://localhost:24813/api/Employee/AddEmployee",
  GetEmployeeById: "http://localhost:24813/api/Employee/GetById/",
  UpdateEmployee: "http://localhost:24813/api/Employee/UpdateEmployee",
  DeleteEmployee: "http://localhost:24813/api/Employee/DeleteEmployee/",
  GetEmployeesByHospitalId: "http://localhost:24813/api/Employee/GetEmployeesByHospitalId/",
  GetEmployeesEngineersByHospitalId: "http://localhost:24813/api/Employee/GetEmployeesEngineersByHospitalId/",
  GetEmployeesHasEngRoleInHospital: "http://localhost:24813/api/Employee/GetEmployeesHasEngRoleInHospital/",
  GetEmployeesHasEngDepManagerRoleInHospital: "http://localhost:24813/api/Employee/GetEmployeesHasEngDepManagerRoleInHospital/",
  GetEmployeesAssetOwnerByHospitalId: "http://localhost:24813/api/Employee/GetEmployeesAssetOwnerByHospitalId/",
  GetEmployeesAssetOwnerByHospitalAndAssetDetailId: "http://localhost:24813/api/Employee/GetEmployeesAssetOwnerByHospitalAndAssetDetailId/",
  GetUnregisteredUsers: "http://localhost:24813/api/Employee/GetUnregisteredUsers/",
  GetUnregisteredEngineerUsers: "http://localhost:24813/api/Engineer/GetUnregisteredEngineerUsers/",
  CreatePMAssetTask: "http://localhost:24813/api/PMAssetTask/AddPMAssetTask",
  sortEmployees: "http://localhost:24813/api/Employee/SortEmployees/",
  GetPMAssetTimeById: "http://localhost:24813/api/PMAssetTime/GetById/",
  UpdatePMAssetTime: "http://localhost:24813/api/PMAssetTime/UpdatePMAssetTime/",
  GetPMAssetTaskByMasterAssetId: "http://localhost:24813/api/PMAssetTask/GetPMAssetTaskByMasterAssetId/",
  GetPMAssetTaskByTaskIdAndMasterAssetId: "http://localhost:24813/api/PMAssetTask/GetPMAssetTaskByTaskIdAndMasterAssetId/",
  DeletePMAssetTask: "http://localhost:24813/api/PMAssetTask/DeletePMAssetTask/",
  ListPMTimes: "http://localhost:24813/api/PMTime/ListPMTimes",

  GenerateMasterContractSerial: 'http://localhost:24813/api/Contract/GenerateMasterContractSerial',
  GetContractAttachmentByMasterContractId: 'http://localhost:24813/api/Contract/GetContractAttachmentByMasterContractId/',

  AlertContractsEndBefore3Months: 'http://localhost:24813/api/Contract/AlertContractsEndBefore3Months/',



  GetRequestDocumentsByRequestTrackingId: 'http://localhost:24813/api/RequestDocument/GetRequestDocumentsByRequestTrackingId/',
  GetLastDocumentForRequestTrackingId: 'http://localhost:24813/api/RequestDocument/GetLastDocumentForRequestTrackingId/',
  GetLastDocumentForWorkOrderTrackingId: 'http://localhost:24813/api/WorkOrderAttachment/GetLastDocumentForWorkOrderTrackingId/',
  RequestType: 'http://localhost:24813/api/RequestType/',
  GetRequestTypeById: "http://localhost:24813/api/RequestType/",
  UpdateRequestType: "http://localhost:24813/api/RequestType/UpdateRequestType/",
  DeleteRequestType: "http://localhost:24813/api/RequestType/DeleteRequestType/",
  GetRequestTypesWithPaging: "http://localhost:24813/api/RequestType/GetRequestTypesWithPaging/",
  CountRequestTypes: "http://localhost:24813/api/RequestType/CountRequestTypes",
  SortRequestTypes: "http://localhost:24813/api/RequestType/SortRequestTypes/",
  Problem: 'http://localhost:24813/api/Problem',
  AddProblem: "http://localhost:24813/api/Problem/AddProblem",
  GetProblemById: "http://localhost:24813/api/Problem/",
  GetProblemBySubProblemId: "http://localhost:24813/api/Problem/GetProblemBySubProblemId/",
  GetProblemByMasterAssetId: "http://localhost:24813/api/Problem/GetProblemByMasterAssetId/",
  UpdateProblem: "http://localhost:24813/api/Problem/",
  DeleteProblem: "http://localhost:24813/api/Problem/",
  GetProblemWithPaging: "http://localhost:24813/api/Problem/GetProblemsWithPaging/",
  getProblemcount: "http://localhost:24813/api/Problem/getcount",
  SubProblem: 'http://localhost:24813/api/SubProblem',
  AddSubProblem: "http://localhost:24813/api/SubProblem/",
  GetSubProblemById: "http://localhost:24813/api/SubProblem/",
  UpdateSubProblem: "http://localhost:24813/api/SubProblem/",
  DeleteSubProblem: "http://localhost:24813/api/SubProblem/",
  GetAllSubProblemsByProblemId: 'http://localhost:24813/api/SubProblem/GetAllSubProblemsByProblemId/',
  GetSubProblemWithPaging: "http://localhost:24813/api/SubProblem/GetSubProblemsWithPaging/",
  getSubProblemcount: "http://localhost:24813/api/SubProblem/getcount",

  AssetWorkOrderTask: 'http://localhost:24813/api/AssetWorkOrderTask',
  DeleteAssetWorkOrderTask: 'http://localhost:24813/api/AssetWorkOrderTask/DeleteAssetWorkOrderTask/',
  GetAllWorkOrdersByHospitalId: 'http://localhost:24813/api/WorkOrder/GetAllWorkOrdersByHospitalId/',
  GetWorkOrdersByHospitalId: 'http://localhost:24813/api/WorkOrder/GetWorkOrdersByHospitalId/',
  GetWOCount: 'http://localhost:24813/api/WorkOrder/getcount/',
  SearchInWorkOrders: "http://localhost:24813/api/WorkOrder/SearchInWorkOrders/",
  SearchInWorkOrdersCount: "http://localhost:24813/api/WorkOrder/SearchInWorkOrdersCount",

  GetWorkOrdersCountByStatusIdAndPaging: "http://localhost:24813/api/WorkOrder/GetWorkOrdersCountByStatusIdAndPaging/",


  ListWorkOrders: "http://localhost:24813/api/WorkOrder/ListWorkOrders/",

  ExportWorkOrdersByStatusId: 'http://localhost:24813/api/WorkOrder/ExportWorkOrdersByStatusId/',
  GetAllWorkOrdersByHospitalStatusId: 'http://localhost:24813/api/WorkOrder/GetAllWorkOrdersByHospitalStatusId/',
  GetWOCountByStatus: 'http://localhost:24813/api/WorkOrder/GetCountByStatus/',
  GenerateWorOrderNumber: 'http://localhost:24813/api/WorkOrder/GenerateWorOrderNumber',
  GetAllAssetWorkOrderTasksByMasterAssetId: 'http://localhost:24813/api/AssetWorkOrderTask/GetAllAssetWorkOrderTasksByMasterAssetId/',
  WorkOrderAttachment: 'http://localhost:24813/api/WorkOrderAttachment',
  GetWorkOrderAttachmentsByWorkOrderTrackingId: 'http://localhost:24813/api/WorkOrderAttachment/GetWorkOrderAttachmentsByWorkOrderTrackingId/',
  uploadWorkOrderDcouments: 'http://localhost:24813/api/WorkOrderAttachment/uploadWorkOrderDcouments/',
  WorkOrder: 'http://localhost:24813/api/WorkOrder',
  CreateCheckedWOPDF: 'http://localhost:24813/api/WorkOrder/CreateCheckedWOPDF',
  CreateWOPDF: 'http://localhost:24813/api/WorkOrder/CreateWOPDF',
  GetworkOrderByUserAssetId: 'http://localhost:24813/api/WorkOrder/GetworkOrderByUserAssetId/',
  GetLastRequestAndWorkOrderByAssetId: 'http://localhost:24813/api/WorkOrder/GetLastRequestAndWorkOrderByAssetId',
  GetLastRequestAndWorkOrderByAssetIdAndRequestId: 'http://localhost:24813/api/WorkOrder/GetLastRequestAndWorkOrderByAssetIdAndRequestId/',
  GetTotalWorkOrdersForAssetInHospital: "http://localhost:24813/api/WorkOrder/GetTotalWorkOrdersForAssetInHospital/",
  PrintWorkOrderById: "http://localhost:24813/api/WorkOrder/PrintWorkOrderById/",
  GetworkOrderByUserId: 'http://localhost:24813/api/WorkOrder/GetworkOrderByUserId/',
  GetWorkOrdersByDateAndStatus: 'http://localhost:24813/api/WorkOrder/GetWorkOrdersByDateAndStatus/',
  GetWorkOrdersByDate: 'http://localhost:24813/api/WorkOrder/GetWorkOrdersByDate/',
  GetAllWorkOrdersByDate: 'http://localhost:24813/api/WorkOrder/GetAllWorkOrdersByDate/',
  CountGetWorkOrdersByDate: 'http://localhost:24813/api/WorkOrder/CountGetWorkOrdersByDate/',
  CountWorkOrdersByHospitalId: 'http://localhost:24813/api/WorkOrder/CountWorkOrdersByHospitalId/',
  CreateWorkOrderAttachments: 'http://localhost:24813/api/WorkOrder/CreateWorkOrderAttachments',
  GetWorkOrderByRequestId: 'http://localhost:24813/api/WorkOrder/GetWorkOrderByRequestId/',
  GetAllWorkOrderFromTrackingByUserId: 'http://localhost:24813/api/WorkOrderTracking/GetAllWorkOrderFromTrackingByUserId/',
  WorkOrderPeriority: 'http://localhost:24813/api/WorkOrderPeriority',
  WorkOrderStatus: 'http://localhost:24813/api/WorkOrderStatus/',
  GetWorkOrderStatusByUserId: 'http://localhost:24813/api/WorkOrderStatus/GetAll/',
  GetAllWOForReportByDate: 'http://localhost:24813/api/WorkOrderStatus/GetAllWOForReportByDate',
  UpdateWorkOrderStatus: 'http://localhost:24813/api/WorkOrderStatus/UpdateWorkOrderStatus',
  ListWOStatusesWithPaging: "http://localhost:24813/api/WorkOrderStatus/GetWOStatusWithPaging",
  GetWOStatusesCount: "http://localhost:24813/api/WorkOrderStatus/getcount",
  SortWOStatuses: "http://localhost:24813/api/WorkOrderStatus/SortWOStatuses/",
  WorkOrderTask: 'http://localhost:24813/api/WorkOrderTask',
  GetAllWorkOrderTaskByWorkOrderId: 'http://localhost:24813/api/WorkOrderTask/GetAllWorkOrderTaskByWorkOrderId/',
  WorkOrderTracking: 'http://localhost:24813/api/WorkOrderTracking/',
  UpdateWorkOrderTracking: 'http://localhost:24813/api/WorkOrderTracking/UpdateWorkOrderTracking',
  DeleteWorkOrderTracking: 'http://localhost:24813/api/WorkOrderTracking/DeleteWorkOrderTracking/',
  GetWorkOrderTrackingById: 'http://localhost:24813/api/WorkOrderTracking/GetWorkOrderTrackingById/',
  AddWorkOrderTracking: 'http://localhost:24813/api/WorkOrderTracking/AddWorkOrderTracking',
  GetFirstTrackForWorkOrderByWorkOrderId: 'http://localhost:24813/api/WorkOrderTracking/GetFirstTrackForWorkOrderByWorkOrderId/',
  sortWorkOrders: 'http://localhost:24813/api/WorkOrder/SortWorkOrders/',
  countSortWorkOrders: 'http://localhost:24813/api/WorkOrder/CountSortWorkOrders/',
  GetEngManagerWhoFirstAssignedWO: 'http://localhost:24813/api/WorkOrderTracking/GetEngManagerWhoFirstAssignedWO/',
  GetAllWorkOrderFromTrackingByServiceRequestId: 'http://localhost:24813/api/WorkOrderTracking/GetAllWorkOrderFromTrackingByServiceRequestId/',
  GetAllWorkOrderFromTrackingByServiceRequestUserId: 'http://localhost:24813/api/WorkOrderTracking/GetAllWorkOrderFromTrackingByServiceRequestUserId/',
  GetAllWorkOrderByWorkOrderId: 'http://localhost:24813/api/WorkOrderTracking/GetAllWorkOrderByWorkOrderId/',
  GetTrackOfWorkOrderByWorkOrderId: 'http://localhost:24813/api/WorkOrderTracking/GetTrackOfWorkOrderByWorkOrderId/',
  GetAllWorkOrderTrackingByWorkOrderId: 'http://localhost:24813/api/WorkOrderTracking/GetAllWorkOrderTrackingByWorkOrderId/',
  WorkOrderType: 'http://localhost:24813/api/WorkOrderType/',
  GetWorkOrderTypeCount: 'http://localhost:24813/api/WorkOrderType/GetCount',
  GetWOTypesWithPaging: 'http://localhost:24813/api/WorkOrderType/GetWOTypesWithPaging',
  SortWorkOrderTypes: 'http://localhost:24813/api/WorkOrderType/SortWorkOrderTypes/',
  WorkOrderAssign: "http://localhost:24813/api/WorkOrderAssign",
  GetAllWorkOrderAssignsByWorkOrederTrackId: "http://localhost:24813/api/WorkOrderAssign/GetAllWorkOrderAssignsByWorkOrederTrackId/",

  AddTaskSchedule: 'http://localhost:24813/api/PMAssetTaskSchedule',
  GetLastDocumentForMasterContractId: 'http://localhost:24813/api/Contract/GetLastDocumentForMasterContractId/',
  DeleteContractAttachment: 'http://localhost:24813/api/Contract/DeleteContractAttachment/',
  ListSupplierExcludeReasons: "http://localhost:24813/api/SupplierExecludeReason/ListSupplierExcludeReasons",
  AddSupplierExecludeReason: "http://localhost:24813/api/SupplierExecludeReason/AddSupplierExecludeReason",
  GetSupplierExecludeReasonById: "http://localhost:24813/api/SupplierExecludeReason/GetById/",
  UpdateSupplierExecludeReason: "http://localhost:24813/api/SupplierExecludeReason/UpdateSupplierExecludeReason",
  DeleteSupplierExecludeReason: "http://localhost:24813/api/SupplierExecludeReason/DeleteSupplierExecludeReason/",
  ListSupplierHoldReasons: "http://localhost:24813/api/SupplierHoldReason/ListSupplierHoldReasons",
  AddSupplierHoldReason: "http://localhost:24813/api/SupplierHoldReason/AddSupplierHoldReason",
  GetSupplierHoldReasonById: "http://localhost:24813/api/SupplierHoldReason/GetById/",
  UpdateSupplierHoldReason: "http://localhost:24813/api/SupplierHoldReason/UpdateSupplierHoldReason",
  DeleteSupplierHoldReason: "http://localhost:24813/api/SupplierHoldReason/DeleteSupplierHoldReason/",
  ListHospitalExcludeReasons: "http://localhost:24813/api/HospitalExecludeReason/ListHospitalExcludeReasons",
  AddHospitalExecludeReason: "http://localhost:24813/api/HospitalExecludeReason/AddHospitalExecludeReason",
  GetHospitalExecludeReasonById: "http://localhost:24813/api/HospitalExecludeReason/GetById/",
  UpdateHospitalExecludeReason: "http://localhost:24813/api/HospitalExecludeReason/UpdateHospitalExecludeReason",
  DeleteHospitalExecludeReason: "http://localhost:24813/api/HospitalExecludeReason/DeleteHospitalExecludeReason/",
  ListHospitalHoldReasons: "http://localhost:24813/api/HospitalHoldReason/ListHospitalHoldReasons",
  AddHospitalHoldReason: "http://localhost:24813/api/HospitalHoldReason/AddHospitalHoldReason",
  GetHospitalHoldReasonById: "http://localhost:24813/api/HospitalHoldReason/GetById/",
  UpdateHospitalHoldReason: "http://localhost:24813/api/HospitalHoldReason/UpdateHospitalHoldReason",
  DeleteHospitalHoldReason: "http://localhost:24813/api/HospitalHoldReason/DeleteHospitalHoldReason/",
  GenerateSupplierExecludeAssetNumber: "http://localhost:24813/api/SupplierExecludeAsset/GenerateSupplierExecludeAssetNumber",
  GetAllSupplierExcludeAssets: "http://localhost:24813/api/SupplierExecludeAsset/GetAllSupplierExcludeAssets",
  GetAttachmentBySupplierExcludeAssetId: "http://localhost:24813/api/SupplierExecludeAsset/GetAttachmentBySupplierExcludeAssetId/",
  AddSupplierExecludeAsset: "http://localhost:24813/api/SupplierExecludeAsset/AddSupplierExecludeAsset",
  GetSupplierExecludeAssetById: "http://localhost:24813/api/SupplierExecludeAsset/GetById/",
  GetSupplierExecludeAssetDetailById: "http://localhost:24813/api/SupplierExecludeAsset/GetSupplierExecludeAssetDetailById/",
  UpdateSupplierExecludeAsset: "http://localhost:24813/api/SupplierExecludeAsset/UpdateSupplierExecludeAsset",
  UpdateSupplierExcludedDate: "http://localhost:24813/api/SupplierExecludeAsset/UpdateExcludedDate",
  DeleteSupplierExecludeAsset: "http://localhost:24813/api/SupplierExecludeAsset/DeleteSupplierExecludeAsset/",


  ListSupplierExecludeAssets: "http://localhost:24813/api/SupplierExecludeAsset/ListSupplierExecludeAssets/",

  CreateSupplierExecludePDF: "http://localhost:24813/api/SupplierExecludeAsset/CreateSupplierExecludePDF/",
  AddSupplierExeclude: "http://localhost:24813/api/SupplierExeclude/AddSupplierExeclude",
  GetSupplierExecludeById: "http://localhost:24813/api/SupplierExeclude/GetById/",
  SendSupplierExcludeEmail: "http://localhost:24813/api/SupplierExeclude/SendSupplierExcludeEmail/",
  GetAllByStatusId: "http://localhost:24813/api/SupplierExecludeAsset/GetAllByStatusId/",
  getSupplierExecludeAssetCount: "http://localhost:24813/api/SupplierExecludeAsset/getcount",
  GetcountByAppTypeId: "http://localhost:24813/api/SupplierExecludeAsset/GetcountByAppTypeId",
  CountListSupplierExcludeAssetsWithPagingWithStatusIdAndTypeId: "http://localhost:24813/api/SupplierExecludeAsset/CountListSupplierExcludeAssetsWithPagingWithStatusIdAndTypeId/",
  GetCountAfterFilterStatusId: "http://localhost:24813/api/SupplierExecludeAsset/GetCountAfterFilterStatusId/",
  SortSuplierApp: "http://localhost:24813/api/SupplierExecludeAsset/SortSuplierApp/",
  ListApplicationTypes: "http://localhost:24813/api/ApplicationType/ListApplicationTypes",
  ListHospitalApplications: "http://localhost:24813/api/HospitalApplication/ListHospitalApplications/",
  AddHospitalApplication: "http://localhost:24813/api/HospitalApplication/AddHospitalApplication",
  GetHospitalApplicationById: "http://localhost:24813/api/HospitalApplication/GetById/",
  GetHospitalApplicationDetailById: "http://localhost:24813/api/HospitalApplication/GetHospitalApplicationById/",



  SendHospitalExcludeEmail: "http://localhost:24813/api/HospitalApplication/SendHospitalExcludeEmail/",
  UpdateHospitalApplication: "http://localhost:24813/api/HospitalApplication/UpdateHospitalApplication",
  UpdateHospitalExcludedDate: "http://localhost:24813/api/HospitalApplication/UpdateExcludedDate",
  DeleteHospitalApplication: "http://localhost:24813/api/HospitalApplication/DeleteHospitalApplication/",
  GenerateHospitalApplicationNumber: "http://localhost:24813/api/HospitalApplication/GenerateHospitalApplicationNumber/",
  GetHospitalApplicationByDate: "http://localhost:24813/api/HospitalApplication/GetHospitalApplicationByDate/",
  CountGetHospitalApplicationByDate: "http://localhost:24813/api/HospitalApplication/CountGetHospitalApplicationByDate/",
  GetSupplierExcludeAssetByDate: "http://localhost:24813/api/HospitalApplication/SearchSupplierExecludeAssetByDate/",
  CountSupplierExcludeAssetByDate: "http://localhost:24813/api/HospitalApplication/CountSearchSupplierExecludeAssetByDate/",
  CreateHospitalApplicationAttachments: "http://localhost:24813/api/HospitalApplication/CreateHospitalApplicationAttachments",
  GetAttachmentByHospitalApplicationId: "http://localhost:24813/api/HospitalApplication/GetAttachmentByHospitalApplicationId/",
  DeleteHospitalApplicationAttachment: "http://localhost:24813/api/HospitalApplication/DeleteHospitalApplicationAttachment/",
  AddHospitalReasonTransaction: "http://localhost:24813/api/HospitalApplicationTransaction/AddHospitalReasonTransaction",
  GetHospitalTransAttachments: "http://localhost:24813/api/HospitalApplicationTransaction/GetAttachments/",
  GetcountByAppTypeIdAndStatusId: "http://localhost:24813/api/HospitalApplication/GetcountByAppTypeIdAndStatusId/",
  GetCountByAppTypeId: "http://localhost:24813/api/HospitalApplication/GetCountByAppTypeId/",
  getHospitalApplicationCount: "http://localhost:24813/api/HospitalApplication/getcount/",
  sortHospitalApp: 'http://localhost:24813/api/HospitalApplication/SortHospitalApp/',
  GetAllHospitalExecludes: 'http://localhost:24813/api/HospitalApplication/GetAllHospitalExecludes/',
  GetAllHospitalHolds: 'http://localhost:24813/api/HospitalApplication/GetAllHospitalHolds/',
  GetAllHospitalsByStatusId: "http://localhost:24813/api/HospitalApplication/GetAllHospitalsByStatusId/",
  GetHospitalCountAfterFilterStatusId: "http://localhost:24813/api/HospitalApplication/GetHospitalCountAfterFilterStatusId/",
  CreateSupplierExecludeAssetAttachments: "http://localhost:24813/api/SupplierExecludeAsset/CreateSupplierExecludeAssetAttachments",
  GetAttachmentBySupplierExecludeAssetId: "http://localhost:24813/api/SupplierExecludeAsset/GetAttachmentBySupplierExecludeAssetId/",
  DeleteSupplierExecludeAssetAttachment: "http://localhost:24813/api/SupplierExecludeAsset/DeleteSupplierExecludeAssetAttachment/",
  GetAllSupplierExecludes: "http://localhost:24813/api/SupplierExecludeAsset/GetAllSupplierExecludes/",
  GetAllSupplierHolds: "http://localhost:24813/api/SupplierExecludeAsset/GetAllSupplierHolds/",
  ListMasterAssetComponents: "http://localhost:24813/api/MasterAssetComponent/ListMasterAssetComponents",



  GetMasterAssetComponentById: "http://localhost:24813/api/MasterAssetComponent/GetById/",
  GetMasterAssetComponentByMasterAssetId: "http://localhost:24813/api/MasterAssetComponent/GetMasterAssetComponentByMasterAssetId/",
  ViewMasterAssetComponentById: "http://localhost:24813/api/MasterAssetComponent/ViewMasterAssetComponent/",
  UpdateMasterAssetComponent: "http://localhost:24813/api/MasterAssetComponent/UpdateMasterAssetComponent",
  AddMasterAssetComponent: "http://localhost:24813/api/MasterAssetComponent/AddMasterAssetComponent",
  DeleteMasterAssetComponent: "http://localhost:24813/api/MasterAssetComponent/DeleteMasterAssetComponent/",
  GetAllVisits: "http://localhost:24813/api/Visit/GetAllVisits",
  GetVisitById: "http://localhost:24813/api/Visit/GetById/",
  ViewVisitById: "http://localhost:24813/api/Visit/ViewVisitById/",
  SearchInVisits: "http://localhost:24813/api/Visit/SearchInVisits/",
  SearchInVisitsCount: "http://localhost:24813/api/Visit/SearchInVisitsCount",
  AddVisit: "http://localhost:24813/api/Visit/AddVisit",
  SortVisits: "http://localhost:24813/api/Visit/SortVisits/",
  DeleteVisit: "http://localhost:24813/api/Visit/DeleteVisit/",
  UpdateVisit: "http://localhost:24813/api/Visit/UpdateVisit",
  UpdateVer: "http://localhost:24813/api/Visit/UpdateVer",
  ListVisitsWithPaging: "http://localhost:24813/api/Visit/ListVisitsWithPaging",
  getVisitscount: "http://localhost:24813/api/Visit/getcount/",
  GenerateVisitCode: "http://localhost:24813/api/Visit/GenerateVisitCode/",
  GetVisitAttachmentByVisitId: 'http://localhost:24813/api/Visit/GetVisitAttachmentByVisitId/',
  CreateVisitAttachments: 'http://localhost:24813/api/Visit/CreateVisitAttachments/',
  GetAllVisitTypes: "http://localhost:24813/api/VisitType/GetAllVisitTypes",
  GetAllEngineers: "http://localhost:24813/api/Engineer/GetAllEngineers",
  UpdateEngineer: "http://localhost:24813/api/Engineer/UpdateEngineer",
  ListEngineers: "http://localhost:24813/api/Engineer/ListEngineers",
  ListEngineersWithPaging: "http://localhost:24813/api/Engineer/ListEngineersWithPaging/",
  GetEngineerById: "http://localhost:24813/api/Engineer/GetById/",
  GetByEmail: "http://localhost:24813/api/Engineer/GetByEmail/",
  getEngineerscount: "http://localhost:24813/api/Engineer/getcount/",
  AddEngineer: "http://localhost:24813/api/Engineer/AddEngineer",
  DeleteEngineer: "http://localhost:24813/api/Engineer/DeleteEngineer/",
  sortEngineers: "http://localhost:24813/api/Engineer/SortEngineers/",
  GetAllScraps: "http://localhost:24813/api/Scrap/GetAllScraps/",
  GetScrapById: "http://localhost:24813/api/Scrap/GetById/",
  GetScrapById2: "http://localhost:24813/api/Scrap/GetById2/",

  ViewScrapById: "http://localhost:24813/api/Scrap/ViewScrapById/",
  SearchInScraps: "http://localhost:24813/api/Scrap/SearchInScraps/",
  CreateScrapPDF: "http://localhost:24813/api/Scrap/CreateScrapPDF/",
  CreateScrapCheckedPDF: "http://localhost:24813/api/Scrap/CreateScrapCheckedPDF/",
  SearchInScrapsCount: "http://localhost:24813/api/Scrap/SearchInScrapsCount",
  AddScrap: "http://localhost:24813/api/Scrap/AddScrap",
  SortScraps: "http://localhost:24813/api/Scrap/SortScraps/",
  ListScraps: "http://localhost:24813/api/Scrap/ListScraps/",
  ListScrapsWithPaging: "http://localhost:24813/api/Scrap/ListScrapsWithPaging",
  GetAllScrapsWithPaging: "http://localhost:24813/api/Scrap/GetAllScrapsWithPaging/",

  getScrapscount: "http://localhost:24813/api/Scrap/getcount/",
  GetScrapAttachmentByScrapId: 'http://localhost:24813/api/Scrap/GetScrapAttachmentByScrapId/',
  CreateScrapAttachments: 'http://localhost:24813/api/Scrap/CreateScrapAttachments/',
  GenerateScrapNumber: 'http://localhost:24813/api/Scrap/GenerateScrapNumber',
  DeleteScrap: "http://localhost:24813/api/Scrap/DeleteScrap/",
  GetAllScrapReasons: "http://localhost:24813/api/ScrapReason/GetAllScrapReasons",
  GetScrapReasonByScrapId: 'http://localhost:24813/api/Scrap/GetScrapReasonByScrapId/',
  ListExternalFixes: 'http://localhost:24813/api/ExternalFix/ListExternalFixes',
  GetAllWithPaging: 'http://localhost:24813/api/ExternalFix/GetAllWithPaging/',
  SearchInExternalFix: 'http://localhost:24813/api/ExternalFix/SearchInExternalFix/',
  SortExternalFix: 'http://localhost:24813/api/ExternalFix/SortExternalFix/',
  GetAssetsExceed72HoursInExternalFix: 'http://localhost:24813/api/ExternalFix/GetAssetsExceed72HoursInExternalFix/',
  AddExternalFix: 'http://localhost:24813/api/ExternalFix/AddExternalFix',
  GenerateExternalFixNumber: 'http://localhost:24813/api/ExternalFix/GenerateExternalFixNumber',
  CreateExternalFixFile: 'http://localhost:24813/api/ExternalFix/CreateExternalFixFile',
  ViewExternalFixById: 'http://localhost:24813/api/ExternalFix/ViewExternalFixById/',
  EditExternalFix: 'http://localhost:24813/api/ExternalFix/UpdateExternalFixFile',
  DeleteExternalFix: 'http://localhost:24813/api/ExternalFix/DeleteExternalFix',
  GetAllStockTakingScheduleWithPaging: 'http://localhost:24813/api/StockTakingSchedule/GetAllWithPaging/',
  SearchStockTackingSchedule: 'http://localhost:24813/api/StockTakingSchedule/SearchStockTackingSchedule/',
  SortStockTakingSchedule: 'http://localhost:24813/api/StockTakingSchedule/SortStockTakingSchedule/',
  ListAssetStockTakings: 'http://localhost:24813/api/AssetStockTaking/ListAssetStockTakings/',
  SearchAssetStockTakings: 'http://localhost:24813/api/AssetStockTaking/SearchAssetStockTakings/',
  ListStockTakingSchedules: 'http://localhost:24813/api/StockTakingSchedule/ListStockTakingSchedules',
  DeleteStockTakingSchedule: 'http://localhost:24813/api/StockTakingSchedule/DeleteStockTakingSchedule',
  CreateStockTakingSchedule: 'http://localhost:24813/api/StockTakingSchedule/AddStockTakingSchedule',
  GenerateStockScheduleTakingNumber: "http://localhost:24813/api/StockTakingSchedule/GenerateStockScheduleTakingNumberVM",
  GetStockTakingScheduleById: "http://localhost:24813/api/StockTakingSchedule/GetStockTakingScheduleById",
  GetHospitalsByScheduleId: "http://localhost:24813/api/StockTakingHospital/GetHospitalsByScheduleId",

  CreateManfacturerAssetTimes: "http://localhost:24813/api/ManufacturerPMAsset/CreateManfacturerAssetTimes",
  GetAllManfacturerPMAssetTimes: "http://localhost:24813/api/ManufacturerPMAsset/GetAll",
  SearchManfacturerAssetTimes: "http://localhost:24813/api/ManufacturerPMAsset/SearchManfacturerAssetTimes",
  GetAllForManfacturerCalendar: "http://localhost:24813/api/ManufacturerPMAsset/GetAllForManfacturerCalendar",
  SortManfacturerAssetTimes: "http://localhost:24813/api/ManufacturerPMAsset/SortManfacturerAssetTimes",
  GetManfacturerAssetById: "http://localhost:24813/api/ManufacturerPMAsset/GetManfacturerAssetById",
  UpdateManfacturerAssetTime: "http://localhost:24813/api/ManufacturerPMAsset/UpdateManfacturerAssetTime",
  GetManfacturerAssetModelById: "http://localhost:24813/api/ManufacturerPMAsset/GetManfacturerAssetModelById",
  GetAllManfacturerAssetsTimes: "http://localhost:24813/api/ManufacturerPMAsset/GetAllManfacturerAssetsTimes2",
  CreateAssetFiscalTimes: "http://localhost:24813/api/WNAssetTimes/CreateAssetFiscalTimes/",
  GetFiscalYearQuarters: "http://localhost:24813/api/WNAssetTimes/GetFiscalYearQuarters",
  GetLastDocumentForMsterAssetId: "http://localhost:24813/api/MasterAsset/GetLastDocumentForMsterAssetId/",


  SearchAssetMovement: "http://localhost:24813/api/AssetMovement/SearchAssetMovement/",
  SearchExternalAssetMovement: "http://localhost:24813/api/ExternalAssetMovement/SearchExternalAssetMovement/",

  GetFiscalYearCurrentQuarter: "http://localhost:24813/api/WNAssetTimes/GetFiscalYearCurrentQuarter",
  GenerateHospitalCode: "http://localhost:24813/api/Hospital/GenerateHospitalCode",
  GenerateBrandCode: "http://localhost:24813/api/Brand/GenerateBrandCode",
  GenerateSupplierCode: "http://localhost:24813/api/Supplier/GenerateSupplierCode",
  GenerateDepartmentCode: "http://localhost:24813/api/Department/GenerateDepartmentCode",
  AutoCompleteBrandName: "http://localhost:24813/api/Brand/AutoCompleteBrandName/",
  GetHospitalByGovId: "http://localhost:24813/api/Hospital/GetHospitalByGovId/",


  
  GenerateWOPMDocument: 'http://localhost:24813/api/AssetDetail/GenerateWOPMDocument',


  GenerateWOPMDocumentByDepartment: 'http://localhost:24813/api/AssetDetail/GenerateWOPMDocumentByDepartment',
};